"""Prompts and checks for riddles generated by the local App Lab LLM."""
import json
import logging
import re

MODEL = 'llamacpp:Qwen3.5-0.8B-Q4_0'
SYSTEM_PROMPT = (
    'Turn the facts into a first-person riddle for a guessing game. '
    'Use two short English sentences, under 30 words. '
    'Only describe the supplied facts. Start with "I". '
    'Do not name the object or give the answer. Output only the riddle.'
)
log = logging.getLogger('scavenger.clues')


def generate_clue(llm, target):
    # Each request is independent, including after a timeout or rejected reply.
    llm.clear_memory()
    text = llm.chat(f"Facts: {target['riddle_facts']}")
    log.info('clue_model_reply target=%s text=%s', target['label'], json.dumps(text))
    if not isinstance(text, str):
        raise ValueError('The model did not return text')
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.S).strip().strip('"“”')
    text = ' '.join(text.split())
    if not 20 <= len(text) <= 260 or not 5 <= len(text.split()) <= 45:
        raise ValueError('The generated riddle has an unsuitable length')
    if '<' in text or '>' in text or text[-1] not in '.?!' or re.search(r'\b(answer|riddle)\s*:', text, re.I):
        raise ValueError('The model returned incomplete text or commentary')
    for answer in {target['name'].lower(), target['label'].replace('_', ' ').lower()}:
        if re.search(r'\b' + re.escape(answer) + r'(?:s|es)?\b', text, re.I):
            raise ValueError('The generated riddle reveals the answer')
    return text
